### ISSUE TITLE
Configuration of plexus-archiver

### ISSUE THREAD

**Issue by khmarbaise** [codehaus-plexus/plexus-archiver#50]
I would like to know if the plexus-archiver can somehow configured via properties or via setters (zipArchiver) to get more performance for large zip files (ca. 10 GiB)...?

**Comment by plamentotev** [comment]
Hi,

Short answer - no, don't think so. More details in the rest of the answer.

Would you please explain with a bit more details what you have in mind? How does the file size affects the performance. Do you experience extensive slowdown when the file size grows? Do you experience the slow down when you only store the files (no compression ZIP file).

The `AbstractZipArchiver` depends on the Apache Commons Compress's Zip implementation. And it only allows you to choose the compression method - otherwise I don't see any other performance related configuration related to the zip format itself. On other hand the zip file is created in parallel - here we have two parameters that could affect the performance. The first is the number of parallel threads (set to `Runtime.getRuntime().availableProcessors()`). The second is the numbers of bytes kept in the memory - once the threshold is exceeded the bytes are written to the disk. But not sure how those two are related to the zip file size - they could affect the performance of course but the effect should be the same and the file size should not matter - 1GiB or 10GiB. Or I'm wrong here?

None of the above mentioned option is configurable with the exception of the compress method - you could configure plexus archiver only to store the files.

**Comment by khmarbaise** [comment]
So I have tested plexus-archiver 2.9.1 in comparison to 3.4 with ZIP files for ca. 10 GiB in size. The version 3.4 reduces the runtime to build such zip file from 12 minutes to 6 minutes..which is an enormous performance increase...I though there could some options to increase the size which is kept in memory which might have improved the performance....

**Comment by plamentotev** [comment]
2.9.1 creates the ZIP archive in single thread, while 3.4 does that in parallel. I guess that is what makes it faster. For the 2.x branch the parallel ZIP creation is introduced with 2.10

**Comment by krosenvold** [comment]
I did some tests and did not really find that increasing memory buffer size
improved performance further. But I did not test with such a large file.

Kristian


2016-08-21 10:01 GMT+02:00 Plamen Totev <notifications@github.com>:
